### ISSUE TITLE
Aminer.mat dataset?

### ISSUE THREAD

**Issue by xuChenSJTU** [didi/hetsann#1]
Dear authors,

Thanks for sharing the code for this excellent paper.

I want to learn from this.

Could you give me the Aminer.mat data file?

Thanks.

Xu Chen

**Comment by xhhszc** [comment]
The Aminer dataset has been uploaded.

**Comment by xhhszc** [comment]
> Dear authors,
> 
> Thanks for sharing the code for this excellent paper.
> 
> I want to learn from this.
> 
> Could you give me the Aminer.mat data file?
> 
> Thanks.
> 
> Xu Chen
