### ISSUE TITLE
unable to load Aminer dataset 

### ISSUE THREAD

**Issue by shirinmous** [didi/hetsann#7]
Hi and thanks for sharing your great work.
I have a problem in loading Aminer dataset.
When I load that .mat file with scipy io package (your code) I get this error: Unknown mat file type, version 52, 56
and when I load that file in Matlab I get this error: Unable to read MAT-file ... Not a binary MAT-file. Try load
-ASCII to read as text.

**Comment by xhhszc** [comment]
> Hi and thanks for sharing your great work.
> I have a problem in loading Aminer dataset.
> When I load that .mat file with scipy io package (your code) I get this error: Unknown mat file type, version 52, 56
> and when I load that file in Matlab I get this error: Unable to read MAT-file ... Not a binary MAT-file. Try load
> -ASCII to read as text.

**Comment by xhhszc** [comment]
> Hi and thanks for sharing your great work.
> I have a problem in loading Aminer dataset.
> When I load that .mat file with scipy io package (your code) I get this error: Unknown mat file type, version 52, 56
> and when I load that file in Matlab I get this error: Unable to read MAT-file ... Not a binary MAT-file. Try load
> -ASCII to read as text.

**Comment by xhhszc** [comment]
> Hi and thanks for sharing your great work.
> I have a problem in loading Aminer dataset.
> When I load that .mat file with scipy io package (your code) I get this error: Unknown mat file type, version 52, 56
> and when I load that file in Matlab I get this error: Unable to read MAT-file ... Not a binary MAT-file. Try load
> -ASCII to read as text.

Hi, the Aminer data file have been stored with Git LFS, please  solve it before you load the data.

**Comment by shirinmous** [comment]
Thanks a lot.
